### ISSUE TITLE
Hope for last milestone test.

### ISSUE THREAD

**Issue by martindekov** [martindekov/push2#10]
Just test.

**Comment by martindekov** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by martindekov** [comment]
Derek set milestone: No luck

**Comment by martindekov** [comment]
Derek set milestone:

**Comment by martindekov** [comment]
Derek set milestone: Another milestone

**Comment by martindekov** [comment]
Derek remove milestone: Another milestone

**Comment by martindekov** [comment]
Derek set milestone:

**Comment by martindekov** [comment]
Derek set milestone: No luck

**Comment by martindekov** [comment]
Derek remove milestone: Another milestone

**Comment by martindekov** [comment]
Derek remove milestone:
