### ISSUE TITLE
Mil2

### ISSUE THREAD

**Issue by martindekov** [martindekov/push2#8]
Mil test.

**Comment by mrtind** [comment]
Derek set milestone: Another issue

**Comment by mrtind** [comment]
Derek set milestone: Another milestone

**Comment by mrtind** [comment]
Derek remove milestone: Another milestone

**Comment by mrtind** [comment]
Derek add milestone: Another milestone

**Comment by mrtind** [comment]
Derek remove milestone: Another milestone

**Comment by mrtind** [comment]
Derek set milestone: Another milestone

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by mrtind** [comment]
Derek remove milestone: No luck

**Comment by mrtind** [comment]
Derek remove milestone: No luck

**Comment by mrtind** [comment]
Derek remove milestone: No luck

**Comment by mrtind** [comment]
Derek remove milestone: No luck

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by martindekov** [comment]
Derek remove milestone: No luck

**Comment by martindekov** [comment]
Derek set milestone: Another milestone

**Comment by martindekov** [comment]
Derek remove milestone: Another milestone

**Comment by mrtind** [comment]
Derek remove milestone: Another milestone

**Comment by martindekov** [comment]
Derek set milestone: Another milestone

**Comment by martindekov** [comment]
Derek remove milestone: Another milestone

**Comment by martindekov** [comment]
Derek remove milestone: Another milestone

**Comment by mrtind** [comment]
Derek set milestone: Another milestone

**Comment by mrtind** [comment]
Derek set milestone: Another milestone

**Comment by mrtind** [comment]
Derek set milestone: No luck

**Comment by martindekov** [comment]
Derek set milestone: Another milestone

**Comment by martindekov** [comment]
Derek set milestone: Another milestone

**Comment by martindekov** [comment]
Derek set milestone: No luck
